export default async function handler(request, res) {

    var EventsList = 
    [
      {
        "name": "Cats",
        "line": "Just a Cat Staring at You",
        "line2": "Animal",
        "media": "Pet",
        "image1": "https://c.pxhere.com/photos/88/8a/cat_lying_blue_eye_small_ginger_fur_heal_pet_animal-609263.jpg!d",
        "image2": "https://c.pxhere.com/photos/88/8a/cat_lying_blue_eye_small_ginger_fur_heal_pet_animal-609263.jpg!d",
        "sepia": false,
        "greyscale": false,
        "tvColorStage": "#9b59b6",
        "tvTopColor": "#bf00bf",
        "tvTopColor2": "#00bfbf",
        "tvTopColor3": "#cd4aad",
        "tvTopColor4": "#bfbfbf",
        "tvTopColor5": "#bfbf00",
        "tvTopColor6": "#cd4aad",
        "tvTopColor7": "#00bf00",
        "tvBotColor": "#0000bf",
        "tvBotColor2": "#00bfbf",
        "tvBotColor3": "#bf00bf",
        "tvBotColor4": "#cd4aad",
        "tvBotColor5": "#000000",
        "tvBotColor6": "#000000",
        "tvBotColor7": "#cd4aad",
        "background": "#aaed4f",
        "knobcolor": "#cbcaca",
        "fontcolor": "#000000",
      },
      {
        "name": "LL",
        "line": "Ruler of the World",
        "line2": "Code Geass",
        "media": "Anime",
        "image1": "https://images6.fanpop.com/image/photos/36400000/Anime-Geniuses-image-anime-geniuses-36425181-2000-2000.jpg",
        "image2": "https://images6.fanpop.com/image/photos/36400000/Anime-Geniuses-image-anime-geniuses-36425181-2000-2000.jpg",
        "sepia": false,
        "greyscale": false,
        "tvColorStage": "#9b59b6",
        "tvTopColor": "#bf00bf",
        "tvTopColor2": "#00bfbf",
        "tvTopColor3": "#0000bf",
        "tvTopColor4": "#bfbfbf",
        "tvTopColor5": "#bfbf00",
        "tvTopColor6": "#bf0000",
        "tvTopColor7": "#00bf00",
        "tvBotColor": "#0000bf",
        "tvBotColor2": "#00bfbf",
        "tvBotColor3": "#bf00bf",
        "tvBotColor4": "#bfbfbf",
        "tvBotColor5": "#000000",
        "tvBotColor6": "#000000",
        "tvBotColor7": "#000000",
        "background": "#f2f2f2",
        "knobcolor": "#cbcaca",
        "fontcolor": "#000000",
      },
      {
        "name": "Snivy",
        "line": "The Grass Vine Pokemon",
        "line2": "Pokemon",
        "media": "PKMN",
        "image1": "https://vignette.wikia.nocookie.net/tmnt-x-pokemon/images/9/94/Snivy.full.2180729.jpg/revision/latest?cb=20180107032017",
        "image2": "https://vignette.wikia.nocookie.net/tmnt-x-pokemon/images/9/94/Snivy.full.2180729.jpg/revision/latest?cb=20180107032017",
        "sepia": false,
        "greyscale": false,
        "tvColorStage": "#5edba0",
        "tvTopColor": "#bf00bf",
        "tvTopColor2": "#00bfbf",
        "tvTopColor3": "#0000bf",
        "tvTopColor4": "#bfbfbf",
        "tvTopColor5": "#bfbf00",
        "tvTopColor6": "#cbcaca",
        "tvTopColor7": "#00bf00",
        "tvBotColor": "#0000bf",
        "tvBotColor2": "#00bfbf",
        "tvBotColor3": "#bf00bf",
        "tvBotColor4": "#bfbfbf",
        "tvBotColor5": "#000000",
        "tvBotColor6": "#000000",
        "tvBotColor7": "#000000",
        "background": "#d1c979",
        "knobcolor": "#cbcaca",
        "fontcolor": "#000000",
      },
      {
        "name": "Paimon",
        "line": "Emergency Food",
        "line2": "Menace to Society",
        "media": "Menace",
        "image1": "https://zeldauniverse.net/wp-content/uploads/2021/01/Paimon.jpeg",
        "image2": "https://zeldauniverse.net/wp-content/uploads/2021/01/Paimon.jpeg",
        "sepia": false,
        "greyscale": false,
        "tvColorStage": "#c63d49",
        "tvTopColor": "#bf00bf",
        "tvTopColor2": "#00bfbf",
        "tvTopColor3": "#0000bf",
        "tvTopColor4": "#bfbfbf",
        "tvTopColor5": "#bfbf00",
        "tvTopColor6": "#d1c979",
        "tvTopColor7": "#00bf00",
        "tvBotColor": "#0000bf",
        "tvBotColor2": "#00bfbf",
        "tvBotColor3": "#bf00bf",
        "tvBotColor4": "#bfbfbf",
        "tvBotColor5": "#000000",
        "tvBotColor6": "#d1c979",
        "tvBotColor7": "#000000",
        "background": "#f2f2f2",
        "knobcolor": "#cbcaca",
        "fontcolor": "#000000",
      },
      {
        "name": "Kindred",
        "line": "The Harbingers of Death",
        "line2": "League of Legends",
        "media": "Death",
        "image1": "https://cdn.mmohuts.com/wp-content/gallery/league-kindred-review-gallery/LegaueOfLegendsKindredReview.jpg",
        "image2": "https://cdn.mmohuts.com/wp-content/gallery/league-kindred-review-gallery/LegaueOfLegendsKindredReview.jpg",
        "sepia": false,
        "greyscale": false,
        "tvColorStage": "#c63d49",
        "tvTopColor": "#bf00bf",
        "tvTopColor2": "#00bfbf",
        "tvTopColor3": "#0000bf",
        "tvTopColor4": "#bfbfbf",
        "tvTopColor5": "#bfbf00",
        "tvTopColor6": "#bf0000",
        "tvTopColor7": "#00bf00",
        "tvBotColor": "#0000bf",
        "tvBotColor2": "#00bfbf",
        "tvBotColor3": "#00bf00",
        "tvBotColor4": "#bfbfbf",
        "tvBotColor5": "#000000",
        "tvBotColor6": "#000000",
        "tvBotColor7": "#00bf00",
        "background": "#bf00bf",
        "knobcolor": "#cbcaca",
        "fontcolor": "#000000",
      },
    ];
  
    res.setHeader('Cache-Control', 'max-age=0, s-maxage=1800');
    res.setHeader("Access-Control-Allow-Credentials", "true");
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "GET,OPTIONS,PATCH,DELETE,POST,PUT");
    res.setHeader("Access-Control-Allow-Headers", "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version");
    res.json(EventsList);
  }