export default async function handler(request, res) {

    var EventBadges = 
    [
      {
        "name": "Bryan",
        "line2": "head honcho",
        "line3": "visual thinkery",
        "media": "Media",
        "mainimage": "https://c.pxhere.com/photos/88/8a/cat_lying_blue_eye_small_ginger_fur_heal_pet_animal-609263.jpg!d",
        "secimage": "https://c.pxhere.com/photos/88/8a/cat_lying_blue_eye_small_ginger_fur_heal_pet_animal-609263.jpg!d",
        "sepia": false,
        "bw": true,
        "tvcolor": "#c63d49",
        "topcolor1": "#bf00bf",
        "topcolor2": "#00bfbf",
        "topcolor3": "#0000bf",
        "topcolor4": "#bfbfbf",
        "topcolor5": "#bfbf00",
        "topcolor6": "#bf0000",
        "topcolor7": "#00bf00",
        "bottomcolor1": "#0000bf",
        "bottomcolor2": "#00bfbf",
        "bottomcolor3": "#bf00bf",
        "bottomcolor4": "#bfbfbf",
        "bottomcolor5": "#000000",
        "bottomcolor6": "#000000",
        "bottomcolor7": "#000000",
        "backgroundcolor": "#f2f2f2",
        "knobscolor": "#cbcaca",
        "fontcolor": "#000000",
      },
      {
        "name": "LL",
        "line2": "Ruler of the World",
        "line3": "Code Geass",
        "media": "Anime",
        "mainimage": "https://images6.fanpop.com/image/photos/36400000/Anime-Geniuses-image-anime-geniuses-36425181-2000-2000.jpg",
        "secimage": "https://images6.fanpop.com/image/photos/36400000/Anime-Geniuses-image-anime-geniuses-36425181-2000-2000.jpg",
        "sepia": true,
        "bw": false,
        "tvcolor": "#c63d49",
        "topcolor1": "#bf00bf",
        "topcolor2": "#00bfbf",
        "topcolor3": "#0000bf",
        "topcolor4": "#bfbfbf",
        "topcolor5": "#bfbf00",
        "topcolor6": "#bf0000",
        "topcolor7": "#00bf00",
        "bottomcolor1": "#0000bf",
        "bottomcolor2": "#00bfbf",
        "bottomcolor3": "#bf00bf",
        "bottomcolor4": "#bfbfbf",
        "bottomcolor5": "#000000",
        "bottomcolor6": "#000000",
        "bottomcolor7": "#000000",
        "backgroundcolor": "#f2f2f2",
        "knobscolor": "#cbcaca",
        "fontcolor": "#000000",
      },
      {
        "name": "Snivy",
        "line2": "The Grass Vine Pokemon",
        "line3": "Pokemon",
        "media": "Pokemon",
        "mainimage": "https://vignette.wikia.nocookie.net/tmnt-x-pokemon/images/9/94/Snivy.full.2180729.jpg/revision/latest?cb=20180107032017",
        "secimage": "https://vignette.wikia.nocookie.net/tmnt-x-pokemon/images/9/94/Snivy.full.2180729.jpg/revision/latest?cb=20180107032017",
        "sepia": false,
        "bw": false,
        "tvcolor": "#c63d49",
        "topcolor1": "#bf00bf",
        "topcolor2": "#00bfbf",
        "topcolor3": "#0000bf",
        "topcolor4": "#bfbfbf",
        "topcolor5": "#bfbf00",
        "topcolor6": "#bf0000",
        "topcolor7": "#00bf00",
        "bottomcolor1": "#0000bf",
        "bottomcolor2": "#00bfbf",
        "bottomcolor3": "#bf00bf",
        "bottomcolor4": "#bfbfbf",
        "bottomcolor5": "#000000",
        "bottomcolor6": "#000000",
        "bottomcolor7": "#000000",
        "backgroundcolor": "#f2f2f2",
        "knobscolor": "#cbcaca",
        "fontcolor": "#000000",
      },
      {
        "name": "Paimon",
        "line2": "Emergency Food",
        "line3": "Menace to Society",
        "media": "Menace",
        "mainimage": "https://zeldauniverse.net/wp-content/uploads/2021/01/Paimon.jpeg",
        "secimage": "https://zeldauniverse.net/wp-content/uploads/2021/01/Paimon.jpeg",
        "sepia": false,
        "bw": false,
        "tvcolor": "#c63d49",
        "topcolor1": "#bf00bf",
        "topcolor2": "#00bfbf",
        "topcolor3": "#0000bf",
        "topcolor4": "#bfbfbf",
        "topcolor5": "#bfbf00",
        "topcolor6": "#bf0000",
        "topcolor7": "#00bf00",
        "bottomcolor1": "#0000bf",
        "bottomcolor2": "#00bfbf",
        "bottomcolor3": "#bf00bf",
        "bottomcolor4": "#bfbfbf",
        "bottomcolor5": "#000000",
        "bottomcolor6": "#000000",
        "bottomcolor7": "#000000",
        "backgroundcolor": "#f2f2f2",
        "knobscolor": "#cbcaca",
        "fontcolor": "#000000",
      },
      {
        "name": "Kindred",
        "line2": "The Harbingers of Death",
        "line3": "League of Legends",
        "media": "Death",
        "mainimage": "https://cdn.mmohuts.com/wp-content/gallery/league-kindred-review-gallery/LegaueOfLegendsKindredReview.jpg",
        "secimage": "https://cdn.mmohuts.com/wp-content/gallery/league-kindred-review-gallery/LegaueOfLegendsKindredReview.jpg",
        "sepia": false,
        "bw": false,
        "tvcolor": "#c63d49",
        "topcolor1": "#bf00bf",
        "topcolor2": "#00bfbf",
        "topcolor3": "#0000bf",
        "topcolor4": "#bfbfbf",
        "topcolor5": "#bfbf00",
        "topcolor6": "#bf0000",
        "topcolor7": "#00bf00",
        "bottomcolor1": "#0000bf",
        "bottomcolor2": "#00bfbf",
        "bottomcolor3": "#bf00bf",
        "bottomcolor4": "#bfbfbf",
        "bottomcolor5": "#000000",
        "bottomcolor6": "#000000",
        "bottomcolor7": "#000000",
        "backgroundcolor": "#f2f2f2",
        "knobscolor": "#cbcaca",
        "fontcolor": "#000000",
      },
    ];
  
    res.setHeader('Cache-Control', 'max-age=0, s-maxage=1800');
    res.setHeader("Access-Control-Allow-Credentials", "true");
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "GET,OPTIONS,PATCH,DELETE,POST,PUT");
    res.setHeader("Access-Control-Allow-Headers", "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version");
    res.json(EventBadges);
  }